version: '3.4'

volumes:
  sequencer_geth_data:
  sequencer_node_data:

services:
  sequencer_geth:
    image: morphism-geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
    volumes:
      - "sequencer_geth_data:/db"
      - "${PWD}/jwt-secret.txt:/config/jwt-secret.txt"
      - "${PWD}/genesis_geth.json:/genesis.json"
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"

  sequencer_node:
    depends_on:
      - sequencer_geth
    build:
      context: ..
      dockerfile: ./ops-morphism/Dockerfile
    ports:
      - "26656:26656"
    environment:
      - MORPH_NODE_L2_ETH_RPC=http://sequencer_geth:8545
      - MORPH_NODE_L2_ENGINE_RPC=http://sequencer_geth:8551
      - MORPH_NODE_L2_ENGINE_AUTH=jwt-secret.txt
      ## todo need to replace it to a public network
      - MORPH_NODE_L1_ETH_RPC=http://ec2-18-237-143-251.us-west-2.compute.amazonaws.com:8545
      - MORPH_NODE_SYNC_DEPOSIT_CONTRACT_ADDRESS=0x6900000000000000000000000000000000000001
      ## - MORPH_NODE_SYNC_START_HEIGHT=88854536
    volumes:
      - "sequencer_node_data:/data"
      - "${PWD}/jwt-secret.txt:/jwt-secret.txt"
    entrypoint:
      - "/bin/sh"
      - "/entrypoint.sh"

  tx-submitter:
    depends_on:
      - sequencer_geth
      - sequencer_node
    image: tx-submitter:latest
    command: rollup
    environment:
      - PRIVATE_KEY=ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - L2_RPC_URL=http://sequencer_geth:8545
      - L1_RPC_URL=http://ec2-18-237-143-251.us-west-2.compute.amazonaws.com:8545
      - CONTRACT_ADDRESS=0x6900000000000000000000000000000000000010
      - EVENT_NAME=SubmitBatches
      - ROLLUP_FUNC_NAME=SubmitBatches
      - BATCH_BLOCK_NUM=1
      - BATCH_NUM=1
      - FIRST_TIME=true
      - CHAIN_ID=900